# Generated by Django 6.1.1 on 2026-09-30 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('duration', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.truf')),
            ],
        ),
    ]
