# Generated by Django 6.1.1 on 2026-09-30 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turf_slot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingslot',
            old_name='team_name',
            new_name='customer_name',
        ),
    ]
