# Generated by Django 6.1.1 on 2026-10-07 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_v2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
    ]
